version: 2 

updates: 
  - package-ecosystem: "pip" 
    directory: "/"
    schedule: 
      interval: "weekly"
    target-branch: "main"
    ignore:
      update-types: ["version-update:semver-patch"]